// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsjtfdpjwamphlwfkiyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzanRmZHBqd2FtcGhsd2ZraXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTkzNjIsImV4cCI6MjA2MDI3NTM2Mn0.-mjg9uMdzTFzbakQDPDdisWk71AlZykqmRZvwnEuE00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);